# see D20201012T145430

name: CI docs
# on: [push]
on: [push, pull_request]

jobs:
  build:
    if: |
      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        target: [linux]
        nimVersion: ['1.0.0', '1.2.0']
        include:
          - target: linux
            os: ubuntu-20.04

    name: ${{ matrix.target }} - ${{ matrix.nimVersion }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: get commit message
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          TIM_PR_MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "TIM_PR_MSG=$TIM_PR_MSG" >> $GITHUB_ENV
          echo "TIM_PR_SKIP=$TIM_PR_MSG-${{github.event.head_commit.message}}-${{github.event.pull_request.title}}" >> $GITHUB_ENV

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimVersion }}

      - name: run tests and docs
        shell: bash
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          echo TIM_PR_MSG: $TIM_PR_MSG
          echo TIM_PR_SKIP: $TIM_PR_SKIP
          echo_run nimble test
          echo_run nimble docs
          echo_run cp docs/index.html htmldocs/index2.html

      #   uses: crazy-max/ghaction-github-pages@v1
      #   with:
      #     build_dir: docs2

      - name: Deploy docs
        ## note: it takes a few seconds to take effect after completes
        uses: JamesIves/github-pages-deploy-action@3.6.2

        ## note: refs/heads/pr_simple_1 for push, refs/pull/3/merge for pull_request
        ## github.ref == 'refs/heads/master'
        if: |
          matrix.target == 'linux' && matrix.nimVersion == '1.2.0' && github.event_name == 'pull_request' && !contains(${{ env.TIM_PR_SKIP }}, '[ci skip]')

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: htmldocs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

# TODO: add caching

