# see: https://github.com/jiro4989/setup-nim-action
# for pull_request: github.event.head_commit.message = ""
# for push: github.event.head_commit.message = "push"
# for pull_request: github.event.pull_request.title = "name_of_PR"
# for push: github.event.pull_request.title = "last_commit_msg"

# https://github.com/marketplace/actions/get-latest-commit-on-pr
# https://github.com/marketplace/actions/get-current-pull-request

name: CI docs
# on: [push]
on: [push, pull_request]

    # if: |
    #   !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    # # if: "!contains(github.event.head_commit.message, '[ci skip]')"
    #   # !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    # # if: |
    # #   !contains(format('a{0}b{1}c{2}d', 'x0', 'x1'), '[skip ci]')


jobs:
  build:
    if: |
      !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]')
    strategy:
      fail-fast: false
      matrix:
        # target: [linux, windows, osx]
        target: [linux]
        # [ '1.0.0', '1.2.0', 'stable', 'devel' ]
        nimVersion: ['1.0.0', '1.2.0']
        include:
          - target: linux
            os: ubuntu-20.04
            # os: ubuntu-18.04
            # os: ubuntu-latest
          # - target: windows
          #   os: windows-2019
          # - target: osx
          #   os: macos-10.15

    name: ${{ matrix.target }} - ${{ matrix.nimVersion }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          echo_run pwd
          echo_run ls
          echo_run ls -a
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
          export commitmsg2=$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Get the latest commit on PR
        id: get-latest-commit
        uses: ActionsRML/get-PR-latest-commit@v1.2
      - uses: actions/checkout@master
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimVersion }}
      - name: run tests and docs
        shell: bash
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          echo github.event_name: ${{ github.event_name }}
          echo_run echo latest_commit_message: ${{ steps.get-latest-commit.outputs.latest_commit_message }}
          echo target: ${{ matrix.target }}
          echo head_commit.message: ${{ github.event.head_commit.message }}
          echo pull_request.title: ${{ github.event.pull_request.title }}
          echo github.ref: ${{ github.ref }}
          echo pull_request.head.sha: ${{ github.event.pull_request.head.sha }}
          echo_run nimble test
          echo_run echo "$GITHUB_CONTEXT"
          echo_run env
          echo_run nimble docs
          echo_run cp docs/index.html htmldocs/index2.html

      #   uses: crazy-max/ghaction-github-pages@v1
      #   with:
      #     build_dir: docs2

      - name: Deploy docs
        ## note: it takes a few seconds to take effect after completes
        uses: JamesIves/github-pages-deploy-action@3.6.2

        ## note: refs/heads/pr_simple_1 for push, refs/pull/3/merge for pull_request
        ## github.ref == 'refs/heads/master'
        if: |
          matrix.target == 'linux' && matrix.nimVersion == '1.2.0' && github.event_name == 'pull_request' && !contains(steps.get-latest-commit.outputs.latest_commit_message, '[ci skip]')

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: htmldocs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

# TODO: add caching

