# see D20201012T145430
# D20201012T162358:here

name: CI docs
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [linux]
        nimVersion: ['1.0.0', '1.2.0']
        include:
          - target: linux
            os: ubuntu-20.04

    name: ${{ matrix.target }} - ${{ matrix.nimVersion }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: get commit message
          #echo "TIM_NOSKIP=${{ !contains($TIM_PR_MSG-${{github.event.head_commit.message}}-${{github.event.pull_request.title}}", '[ci skip]')}} >> $GITHUB_ENV
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          TIM_PR_MSG=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "TIM_PR_MSG=$TIM_PR_MSG" >> $GITHUB_ENV
          echo "TIM_PR_SKIP=$TIM_PR_MSG-${{github.event.head_commit.message}}-${{github.event.pull_request.title}}" >> $GITHUB_ENV
          echo "TIM_TMP1=${{env.TIM_PR_MSG}}"
          echo "TIM_NOSKIP=true" >> $GITHUB_ENV
          echo "TIM_DEPLOY=${{ matrix.target == 'linux' && matrix.nimVersion == '1.2.0' && github.event_name == 'push'}}" >> $GITHUB_ENV

      - uses: jiro4989/setup-nim-action@v1
        if: env.TIM_NOSKIP=='true'
        with:
          nim-version: ${{ matrix.nimVersion }}

      - name: run tests and docs
        if: env.TIM_NOSKIP==true
        shell: bash
        run: |
          echo_run() { echo "$@"": " && "$@" ; }
          echo_run echo TIM_TMP1:$TIM_TMP1
          echo_run nimble test
          echo_run nimble docs
          echo_run cp docs/index.html htmldocs/index2.html

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.6.2
        if: env.TIM_NOSKIP=='true' && env.TIM_DEPLOY==true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: htmldocs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

# TODO: add caching
